### ISSUE TITLE
Idea: Support for multiple inverters

### ISSUE THREAD

**Issue by slipx06** [martinville/solarsynk#1]
Hi. Just an idea. The access token allows you to query each inverter by serial number.  It would be useful to be able to input multiple serial numbers and iterate through each inverter's data i.e.

```
sunsynk_serials=("$(bashio::config 'sunsynk_serial1')" "$(bashio::config 'sunsynk_serial2')")

for sunsynk_serial in "${sunsynk_serials[@]}"; do
    if [ -n "$sunsynk_serial" ]; then
        echo "Please wait while curl is fetching input, grid, load, battery & output data for inverter with serial number $sunsynk_serial ..."

        # Perform curl requests for input, grid, load, battery & output data
        curl -s -X GET -H "Content-Type: application/json" -H "authorization: Bearer $ServerAPIBearerToken" "https://api.sunsynk.net/api/v1/inverter/$sunsynk_serial/realtime/input" -o "pvindata_$sunsynk_serial.json"
        curl -s -X GET -H "Content-Type: application/json" -H "authorization: Bearer $ServerAPIBearerToken" "https://api.sunsynk.net/api/v1/inverter/grid/$sunsynk_serial/realtime?sn=$sunsynk_serial" -o "griddata_$sunsynk_serial.json"

etc
```

Since the serial is unique you could append each file,sensor with the serial number. 

Unrelated to this you may want to escape special characters in the password

**Comment by martinville** [comment]
Hey! Thanks for the suggestion, will certainly take a look at it.  Why did I never think of this ;-)

**Comment by martinville** [comment]
I made some changes. I unfortunately could not update this repo with the changes because it may have a negative impact users who's already using this add-on.

For now mirrored it over to --> https://github.com/martinville/solarsynk_test and made the changes to support multiple inverters. Serial numbers has to be separated with a semi colon ; I.E Serial1;Serial2

I'm only able to set this by setting the entity values manually in HA, If you have multiple inverters would you mind testing it ?

PS: I have not yet looked at the password issue.

**Comment by slipx06** [comment]
Thanks. It fetches data for the first inverter but it dies when fetching the second

```
sensor.solarsynk_redacted_pv1_power
sensor.solarsynk_redacted_pv1_voltage
sensor.solarsynk_redacted_pv2_current
sensor.solarsynk_redacted_pv2_power
sensor.solarsynk_redacted_pv2_voltage
sensor.solarsynk_redacted_overall_state
Fetch complete for inverter: redacted

Fetching data for serial:  secondserial
Cleaning up old data.
Please wait while curl is fetching input, grid, load, battery & output data...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Sensors are correctly created in HA for the first inverter

**Comment by martinville** [comment]
Thanks for testing. I noticed you have an extra space in front of of the second serial number. The script does not trim spaces.
format should be serial1;serial2

**Comment by slipx06** [comment]
OK that fixed it. Works great. Thanks for the add-on.
