### ISSUE TITLE
Typo on friendly name

### ISSUE THREAD

**Issue by kitoban** [martinville/solarsynk#3]
sensor.solarsynk_day_battery_discharge friendly name is "Daily Battery Discsharge" 
Minor update needed to "Daily Battery Discharge"

**Comment by martinville** [comment]
Hi Thanks for this.
I have corrected it, but on the new repository : https://github.com/martinville/solarsynkv2

I no longer maintain this one. The new repository has many fixes and additional functionality which includes sending settings back to the inverter. Its recommended to  change to https://github.com/martinville/solarsynkv2

Cheers

Martin
